# Use the repository wrapper:
# 1. Install backend development dependencies: `just api-sync`
# 2. Install and run hooks: `just pre-commit`
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
      - id: check-added-large-files

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.11.13
  #   hooks:
  #     - id: ruff-check
  #     - id: ruff-format
