"""add immutable competition revisions

Revision ID: 13eb10903bd7
Revises: 61f2c8e4a9bd
Create Date: 2026-07-12 10:29:16.059589

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13eb10903bd7"
down_revision = "61f2c8e4a9bd"
branch_labels = None
depends_on = None

BASELINE_TABLE = "competehub_migration_baselines"
BASELINE_KEY = "c5e0e7e0560d.schema_path"
SCHEMA_PATH_LEGACY = "legacy_create_all"
PUBLIC_PREDECESSOR_STATUSES = {"published", "offline", "archived", "cancelled", "expired"}
PRIMARY_NODE_TYPES = {"registration_deadline", "submission_deadline", "competition_start"}


def upgrade():
    if _schema_path() == SCHEMA_PATH_LEGACY:
        return
    _preflight_predecessor_publication()
    _add_unpublished_competition_status()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competition_series",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_competition_series_created_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_series")),
    )
    with op.batch_alter_table("competition_series", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_series_canonical_name"), ["canonical_name"], unique=True
        )

    op.create_table(
        "competition_revisions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column(
            "base_revision_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "revision_status",
            sa.Enum(
                "draft",
                "pending_review",
                "approved",
                "rejected",
                "returned",
                name="competition_revision_status",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("short_title", sa.String(length=120), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("organizer", sa.String(length=255), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("official_url", sa.String(length=1024), nullable=True),
        sa.Column("attachment_url", sa.String(length=1024), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("registration_applicability", sa.String(length=32), nullable=True),
        sa.Column("team_size", sa.String(length=120), nullable=True),
        sa.Column("participant_forms", sa.JSON(), nullable=False),
        sa.Column("major_scope", sa.String(length=32), nullable=True),
        sa.Column("grade_scope", sa.String(length=32), nullable=True),
        sa.Column("suitable_majors", sa.JSON(), nullable=True),
        sa.Column("suitable_grades", sa.JSON(), nullable=True),
        sa.Column("value_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "submitted_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_revision_id"],
            ["competition_revisions.id"],
            name=op.f("fk_competition_revisions_base_revision_id_competition_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_competition_revisions_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_competition_revisions_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["users.id"],
            name=op.f("fk_competition_revisions_submitted_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_revisions")),
        sa.UniqueConstraint("competition_id", "revision_number", name="uq_competition_revision"),
    )
    with op.batch_alter_table("competition_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_revisions_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_revisions_revision_status"),
            ["revision_status"],
            unique=False,
        )
        batch_op.create_index(
            "uq_active_competition_revision",
            ["competition_id"],
            unique=True,
            postgresql_where=sa.text("revision_status IN ('draft', 'pending_review')"),
            sqlite_where=sa.text("revision_status IN ('draft', 'pending_review')"),
        )

    op.create_table(
        "competition_stages",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_revision_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("stage_key", sa.String(length=120), nullable=False),
        sa.Column("stage_type", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("stage_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_revision_id"],
            ["competition_revisions.id"],
            name=op.f("fk_competition_stages_competition_revision_id_competition_revisions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_stages")),
        sa.UniqueConstraint(
            "competition_revision_id", "stage_key", name="uq_competition_revision_stage_key"
        ),
        sa.UniqueConstraint(
            "competition_revision_id", "stage_order", name="uq_competition_revision_stage_order"
        ),
    )
    with op.batch_alter_table("competition_tag_links", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "competition_revision_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.alter_column("competition_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_competition_tag_links_competition_revision_id"),
            ["competition_revision_id"],
            unique=False,
        )
        batch_op.create_unique_constraint(
            "uq_competition_revision_tag", ["competition_revision_id", "tag_id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_competition_tag_links_competition_revision_id_competition_revisions"),
            "competition_revisions",
            ["competition_revision_id"],
            ["id"],
        )

    with op.batch_alter_table("competition_time_nodes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "competition_revision_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "stage_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
            )
        )
        batch_op.add_column(sa.Column("logical_node_key", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("node_revision", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("occurs_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("prominence", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("prominence_override_reason", sa.Text(), nullable=True))
        batch_op.alter_column("competition_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_competition_revision_id"),
            ["competition_revision_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_occurs_at"), ["occurs_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_stage_id"), ["stage_id"], unique=False
        )
        batch_op.create_unique_constraint(
            "uq_competition_revision_node_key", ["competition_revision_id", "logical_node_key"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_competition_time_nodes_competition_revision_id_competition_revisions"),
            "competition_revisions",
            ["competition_revision_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_competition_time_nodes_stage_id_competition_stages"),
            "competition_stages",
            ["stage_id"],
            ["id"],
        )

    with op.batch_alter_table("competitions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "series_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
            )
        )
        batch_op.add_column(sa.Column("edition_label", sa.String(length=120), nullable=True))
        batch_op.add_column(
            sa.Column(
                "published_revision_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("registration_applicability", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(sa.Column("participant_forms", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("major_scope", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("grade_scope", sa.String(length=32), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_competitions_edition_label"), ["edition_label"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competitions_published_revision_id"),
            ["published_revision_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_competitions_series_id"), ["series_id"], unique=False)
        batch_op.create_unique_constraint(
            "uq_competition_series_edition", ["series_id", "edition_label"]
        )
        batch_op.create_foreign_key(
            "fk_competitions_published_revision_id_competition_revisions",
            "competition_revisions",
            ["published_revision_id"],
            ["id"],
            use_alter=True,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_competitions_series_id_competition_series"),
            "competition_series",
            ["series_id"],
            ["id"],
        )

    with op.batch_alter_table("review_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("differences", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("impact", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True))

    _backfill_predecessor_publication()

    with op.batch_alter_table("competition_time_nodes", schema=None) as batch_op:
        batch_op.alter_column("node_revision", existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column("prominence", existing_type=sa.String(length=20), nullable=False)

    with op.batch_alter_table("competitions", schema=None) as batch_op:
        batch_op.alter_column("participant_forms", existing_type=sa.JSON(), nullable=False)

    # ### end Alembic commands ###


def _preflight_predecessor_publication():
    """Reject unattributable rows before any non-transactional SQLite DDL runs."""
    bind = op.get_bind()
    unowned_ids = list(
        bind.execute(
            sa.text(
                """
                SELECT id FROM competitions
                WHERE created_by_id IS NULL
                ORDER BY id
                LIMIT 10
                """
            )
        ).scalars()
    )
    if unowned_ids:
        raise RuntimeError(
            "Cannot migrate competitions without created_by_id; assign an owning user "
            f"before upgrading. Competition ids: {unowned_ids}"
        )


def _add_unpublished_competition_status():
    if op.get_bind().dialect.name != "postgresql":
        return
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE competition_status ADD VALUE IF NOT EXISTS 'unpublished'")


def _backfill_predecessor_publication():
    bind = op.get_bind()
    metadata = sa.MetaData()
    metadata.reflect(
        bind=bind,
        only=[
            "competition_series",
            "competitions",
            "competition_revisions",
            "competition_stages",
            "competition_time_nodes",
            "competition_tag_links",
            "review_records",
        ],
    )
    series = metadata.tables["competition_series"]
    competitions = metadata.tables["competitions"]
    revisions = metadata.tables["competition_revisions"]
    stages = metadata.tables["competition_stages"]
    time_nodes = metadata.tables["competition_time_nodes"]
    tag_links = metadata.tables["competition_tag_links"]
    review_records = metadata.tables["review_records"]

    predecessor_rows = bind.execute(sa.select(competitions).order_by(competitions.c.id)).mappings()
    for edition in predecessor_rows:
        competition_id = edition["id"]
        nodes = list(
            bind.execute(
                sa.select(time_nodes)
                .where(time_nodes.c.competition_id == competition_id)
                .order_by(time_nodes.c.id)
            ).mappings()
        )
        participant_forms = _legacy_participant_forms(edition["participant_form"])
        major_scope = "selected" if edition["suitable_majors"] else "unknown"
        grade_scope = "selected" if edition["suitable_grades"] else "unknown"
        registration_applicability = (
            "applicable"
            if any(node["node_type"].startswith("registration_") for node in nodes)
            else "unknown"
        )
        # The predecessor stored submission and decision evidence in a mutable
        # competition-level row. Capture it before replacing that queue model.
        legacy_reviews = list(
            bind.execute(
                sa.select(review_records)
                .where(
                    review_records.c.target_type == "competition",
                    review_records.c.target_id == competition_id,
                )
                .order_by(review_records.c.id)
            ).mappings()
        )
        series_id = bind.execute(
            series.insert()
            .values(
                canonical_name=_legacy_series_name(edition["title"], competition_id),
                created_by_id=edition["created_by_id"],
                created_at=edition["created_at"],
                updated_at=edition["updated_at"],
            )
            .returning(series.c.id)
        ).scalar_one()
        bind.execute(
            competitions.update()
            .where(competitions.c.id == competition_id)
            .values(
                series_id=series_id,
                edition_label=f"Legacy edition #{competition_id}",
                registration_applicability=registration_applicability,
                participant_forms=participant_forms,
                major_scope=major_scope,
                grade_scope=grade_scope,
                status=(
                    edition["status"]
                    if edition["status"] in PUBLIC_PREDECESSOR_STATUSES
                    else "unpublished"
                ),
            )
        )

        revision_status = _legacy_revision_status(edition["status"])
        review_evidence = _legacy_review_evidence(legacy_reviews, revision_status)
        submitted_by_id = (
            review_evidence["submitted_by_id"]
            if review_evidence is not None and review_evidence["submitted_by_id"] is not None
            else edition["created_by_id"]
        )
        submitted_at = (
            review_evidence["created_at"] if review_evidence is not None else edition["updated_at"]
        )
        decided_at = (
            review_evidence["updated_at"]
            if review_evidence is not None
            and review_evidence["status"] in {"approved", "rejected", "returned"}
            else edition["updated_at"]
        )
        revision_id = bind.execute(
            revisions.insert()
            .values(
                competition_id=competition_id,
                revision_number=1,
                revision_status=revision_status,
                title=edition["title"],
                short_title=edition["short_title"],
                category=edition["category"],
                organizer=edition["organizer"],
                host=edition["host"],
                source_name=edition["source_name"],
                source_url=edition["source_url"],
                official_url=edition["official_url"],
                attachment_url=edition["attachment_url"],
                summary=edition["summary"],
                detail=edition["detail"],
                eligibility=edition["eligibility"],
                registration_applicability=registration_applicability,
                team_size=edition["team_size"],
                participant_forms=participant_forms,
                major_scope=major_scope,
                grade_scope=grade_scope,
                suitable_majors=edition["suitable_majors"],
                suitable_grades=edition["suitable_grades"],
                value_notes=edition["value_notes"],
                created_by_id=edition["created_by_id"],
                submitted_by_id=(submitted_by_id if revision_status != "draft" else None),
                submitted_at=(submitted_at if revision_status != "draft" else None),
                decided_at=(decided_at if revision_status in {"approved", "rejected"} else None),
                published_at=(decided_at if revision_status == "approved" else None),
                created_at=edition["created_at"],
                updated_at=edition["updated_at"],
            )
            .returning(revisions.c.id)
        ).scalar_one()

        for legacy_review in legacy_reviews:
            if legacy_review["status"] == "pending":
                bind.execute(
                    review_records.delete().where(review_records.c.id == legacy_review["id"])
                )
                continue
            bind.execute(
                review_records.update()
                .where(review_records.c.id == legacy_review["id"])
                .values(
                    target_type="competition_revision",
                    target_id=revision_id,
                    submitted_at=legacy_review["created_at"],
                    decided_at=legacy_review["updated_at"],
                )
            )

        stage_id = None
        if nodes:
            stage_id = bind.execute(
                stages.insert()
                .values(
                    competition_revision_id=revision_id,
                    stage_key="legacy-schedule",
                    stage_type="legacy",
                    label="Legacy schedule",
                    stage_order=1,
                    created_at=edition["created_at"],
                    updated_at=edition["updated_at"],
                )
                .returning(stages.c.id)
            ).scalar_one()
        for node in nodes:
            bind.execute(
                time_nodes.update()
                .where(time_nodes.c.id == node["id"])
                .values(
                    competition_revision_id=revision_id,
                    stage_id=stage_id,
                    logical_node_key=f"legacy-node-{node['id']}",
                    node_revision=1,
                    occurs_at=node["due_at"] or node["starts_at"],
                    prominence=(
                        "primary" if node["node_type"] in PRIMARY_NODE_TYPES else "secondary"
                    ),
                )
            )
        bind.execute(
            tag_links.update()
            .where(tag_links.c.competition_id == competition_id)
            .values(competition_revision_id=revision_id)
        )
        if revision_status == "approved":
            bind.execute(
                competitions.update()
                .where(competitions.c.id == competition_id)
                .values(published_revision_id=revision_id)
            )


def _prepare_predecessor_downgrade():
    bind = op.get_bind()
    metadata = sa.MetaData()
    metadata.reflect(
        bind=bind,
        only=[
            "competitions",
            "competition_revisions",
            "competition_tag_links",
            "review_records",
        ],
    )
    competitions = metadata.tables["competitions"]
    revisions = metadata.tables["competition_revisions"]
    tag_links = metadata.tables["competition_tag_links"]
    review_records = metadata.tables["review_records"]

    unpublished_editions = list(
        bind.execute(
            sa.select(competitions.c.id).where(competitions.c.status == "unpublished")
        ).scalars()
    )
    for competition_id in unpublished_editions:
        latest_status = bind.execute(
            sa.select(revisions.c.revision_status)
            .where(revisions.c.competition_id == competition_id)
            .order_by(revisions.c.revision_number.desc())
            .limit(1)
        ).scalar_one_or_none()
        predecessor_status = {
            "pending_review": "pending_review",
            "rejected": "rejected",
        }.get(latest_status, "draft")
        bind.execute(
            competitions.update()
            .where(competitions.c.id == competition_id)
            .values(status=predecessor_status)
        )

    revision_competition = {
        row["id"]: row["competition_id"]
        for row in bind.execute(sa.select(revisions.c.id, revisions.c.competition_id)).mappings()
    }
    terminal_reviews = list(
        bind.execute(
            sa.select(review_records.c.id, review_records.c.target_id).where(
                review_records.c.target_type == "competition_revision"
            )
        ).mappings()
    )
    for review in terminal_reviews:
        competition_id = revision_competition.get(review["target_id"])
        if competition_id is not None:
            bind.execute(
                review_records.update()
                .where(review_records.c.id == review["id"])
                .values(target_type="competition", target_id=competition_id)
            )

    # The predecessor derives its queue from pending ReviewRecord rows, while
    # the new model derives it from revision state. Recreate only for downgrade.
    pending_revisions = list(
        bind.execute(
            sa.select(revisions).where(revisions.c.revision_status == "pending_review")
        ).mappings()
    )
    for pending_revision in pending_revisions:
        competition_id = pending_revision["competition_id"]
        existing_pending = bind.execute(
            sa.select(review_records.c.id).where(
                review_records.c.target_type == "competition",
                review_records.c.target_id == competition_id,
                review_records.c.status == "pending",
            )
        ).scalar_one_or_none()
        if existing_pending is None:
            submitted_at = pending_revision["submitted_at"] or pending_revision["updated_at"]
            bind.execute(
                review_records.insert().values(
                    target_type="competition",
                    target_id=competition_id,
                    submitted_by_id=pending_revision["submitted_by_id"],
                    status="pending",
                    submitted_at=submitted_at,
                    created_at=submitted_at,
                    updated_at=submitted_at,
                )
            )

    unscoped_links = list(
        bind.execute(
            sa.select(tag_links.c.id, tag_links.c.competition_revision_id).where(
                tag_links.c.competition_id.is_(None)
            )
        ).mappings()
    )
    for link in unscoped_links:
        competition_id = revision_competition.get(link["competition_revision_id"])
        if competition_id is not None:
            bind.execute(
                tag_links.update()
                .where(tag_links.c.id == link["id"])
                .values(competition_id=competition_id)
            )


def _legacy_participant_forms(participant_form):
    return [participant_form] if participant_form in {"individual", "team"} else []


def _legacy_series_name(title, competition_id):
    suffix = f" [legacy #{competition_id}]"
    return f"{title[: 255 - len(suffix)]}{suffix}"


def _legacy_revision_status(competition_status):
    if competition_status in PUBLIC_PREDECESSOR_STATUSES:
        return "approved"
    return {
        "pending_review": "pending_review",
        "rejected": "rejected",
    }.get(competition_status, "draft")


def _legacy_review_evidence(legacy_reviews, revision_status):
    expected_statuses = {
        "pending_review": {"pending"},
        "approved": {"approved"},
        "rejected": {"rejected", "returned"},
    }.get(revision_status, set())
    matching = [review for review in legacy_reviews if review["status"] in expected_statuses]
    if matching:
        return matching[-1]
    return legacy_reviews[-1] if legacy_reviews else None


def downgrade():
    if _schema_path() == SCHEMA_PATH_LEGACY:
        return
    _prepare_predecessor_downgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_records", schema=None) as batch_op:
        batch_op.drop_column("decided_at")
        batch_op.drop_column("submitted_at")
        batch_op.drop_column("impact")
        batch_op.drop_column("differences")

    with op.batch_alter_table("competitions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_competitions_series_id_competition_series"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_competitions_published_revision_id_competition_revisions", type_="foreignkey"
        )
        batch_op.drop_constraint("uq_competition_series_edition", type_="unique")
        batch_op.drop_index(batch_op.f("ix_competitions_series_id"))
        batch_op.drop_index(batch_op.f("ix_competitions_published_revision_id"))
        batch_op.drop_index(batch_op.f("ix_competitions_edition_label"))
        batch_op.drop_column("grade_scope")
        batch_op.drop_column("major_scope")
        batch_op.drop_column("participant_forms")
        batch_op.drop_column("registration_applicability")
        batch_op.drop_column("published_revision_id")
        batch_op.drop_column("edition_label")
        batch_op.drop_column("series_id")

    with op.batch_alter_table("competition_time_nodes", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_competition_time_nodes_stage_id_competition_stages"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_competition_time_nodes_competition_revision_id_competition_revisions"),
            type_="foreignkey",
        )
        batch_op.drop_constraint("uq_competition_revision_node_key", type_="unique")
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_stage_id"))
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_occurs_at"))
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_competition_revision_id"))
        batch_op.alter_column("competition_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("prominence_override_reason")
        batch_op.drop_column("prominence")
        batch_op.drop_column("occurs_at")
        batch_op.drop_column("node_revision")
        batch_op.drop_column("logical_node_key")
        batch_op.drop_column("stage_id")
        batch_op.drop_column("competition_revision_id")

    with op.batch_alter_table("competition_tag_links", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_competition_tag_links_competition_revision_id_competition_revisions"),
            type_="foreignkey",
        )
        batch_op.drop_constraint("uq_competition_revision_tag", type_="unique")
        batch_op.drop_index(batch_op.f("ix_competition_tag_links_competition_revision_id"))
        batch_op.alter_column("competition_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("competition_revision_id")

    op.drop_table("competition_stages")
    with op.batch_alter_table("competition_revisions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_active_competition_revision",
            postgresql_where=sa.text("revision_status IN ('draft', 'pending_review')"),
            sqlite_where=sa.text("revision_status IN ('draft', 'pending_review')"),
        )
        batch_op.drop_index(batch_op.f("ix_competition_revisions_revision_status"))
        batch_op.drop_index(batch_op.f("ix_competition_revisions_published_at"))

    op.drop_table("competition_revisions")
    with op.batch_alter_table("competition_series", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competition_series_canonical_name"))

    op.drop_table("competition_series")
    _drop_postgresql_enum("competition_revision_status")
    # ### end Alembic commands ###


def _schema_path():
    if BASELINE_TABLE not in sa.inspect(op.get_bind()).get_table_names():
        return None
    return (
        op.get_bind()
        .execute(
            sa.text(f"SELECT value FROM {BASELINE_TABLE} WHERE key = :key").bindparams(
                key=BASELINE_KEY
            )
        )
        .scalar()
    )


def _drop_postgresql_enum(enum_name):
    if op.get_bind().dialect.name == "postgresql":
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
