"""add immutable competition revisions

Revision ID: 13eb10903bd7
Revises: 61f2c8e4a9bd
Create Date: 2026-07-12 10:29:16.059589

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13eb10903bd7"
down_revision = "61f2c8e4a9bd"
branch_labels = None
depends_on = None

BASELINE_TABLE = "competehub_migration_baselines"
BASELINE_KEY = "c5e0e7e0560d.schema_path"
SCHEMA_PATH_LEGACY = "legacy_create_all"


def upgrade():
    if _schema_path() == SCHEMA_PATH_LEGACY:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competition_series",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_competition_series_created_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_series")),
    )
    with op.batch_alter_table("competition_series", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_series_canonical_name"), ["canonical_name"], unique=True
        )

    op.create_table(
        "competition_revisions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column(
            "base_revision_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "revision_status",
            sa.Enum(
                "draft",
                "pending_review",
                "approved",
                "rejected",
                "returned",
                name="competition_revision_status",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("short_title", sa.String(length=120), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("organizer", sa.String(length=255), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("official_url", sa.String(length=1024), nullable=True),
        sa.Column("attachment_url", sa.String(length=1024), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("registration_applicability", sa.String(length=32), nullable=True),
        sa.Column("team_size", sa.String(length=120), nullable=True),
        sa.Column("participant_forms", sa.JSON(), nullable=False),
        sa.Column("major_scope", sa.String(length=32), nullable=True),
        sa.Column("grade_scope", sa.String(length=32), nullable=True),
        sa.Column("suitable_majors", sa.JSON(), nullable=True),
        sa.Column("suitable_grades", sa.JSON(), nullable=True),
        sa.Column("value_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "submitted_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_revision_id"],
            ["competition_revisions.id"],
            name=op.f("fk_competition_revisions_base_revision_id_competition_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_competition_revisions_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_competition_revisions_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["users.id"],
            name=op.f("fk_competition_revisions_submitted_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_revisions")),
        sa.UniqueConstraint("competition_id", "revision_number", name="uq_competition_revision"),
    )
    with op.batch_alter_table("competition_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_revisions_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_revisions_revision_status"),
            ["revision_status"],
            unique=False,
        )
        batch_op.create_index(
            "uq_active_competition_revision",
            ["competition_id"],
            unique=True,
            postgresql_where=sa.text("revision_status IN ('draft', 'pending_review')"),
            sqlite_where=sa.text("revision_status IN ('draft', 'pending_review')"),
        )

    op.create_table(
        "competition_stages",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_revision_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("stage_key", sa.String(length=120), nullable=False),
        sa.Column("stage_type", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("stage_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_revision_id"],
            ["competition_revisions.id"],
            name=op.f("fk_competition_stages_competition_revision_id_competition_revisions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_stages")),
        sa.UniqueConstraint(
            "competition_revision_id", "stage_key", name="uq_competition_revision_stage_key"
        ),
        sa.UniqueConstraint(
            "competition_revision_id", "stage_order", name="uq_competition_revision_stage_order"
        ),
    )
    with op.batch_alter_table("competition_tag_links", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "competition_revision_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.alter_column("competition_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_competition_tag_links_competition_revision_id"),
            ["competition_revision_id"],
            unique=False,
        )
        batch_op.create_unique_constraint(
            "uq_competition_revision_tag", ["competition_revision_id", "tag_id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_competition_tag_links_competition_revision_id_competition_revisions"),
            "competition_revisions",
            ["competition_revision_id"],
            ["id"],
        )

    with op.batch_alter_table("competition_time_nodes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "competition_revision_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "stage_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
            )
        )
        batch_op.add_column(sa.Column("logical_node_key", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("node_revision", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("occurs_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("prominence", sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column("prominence_override_reason", sa.Text(), nullable=True))
        batch_op.alter_column("competition_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_competition_revision_id"),
            ["competition_revision_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_occurs_at"), ["occurs_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_stage_id"), ["stage_id"], unique=False
        )
        batch_op.create_unique_constraint(
            "uq_competition_revision_node_key", ["competition_revision_id", "logical_node_key"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_competition_time_nodes_competition_revision_id_competition_revisions"),
            "competition_revisions",
            ["competition_revision_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_competition_time_nodes_stage_id_competition_stages"),
            "competition_stages",
            ["stage_id"],
            ["id"],
        )

    with op.batch_alter_table("competitions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "series_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
            )
        )
        batch_op.add_column(sa.Column("edition_label", sa.String(length=120), nullable=True))
        batch_op.add_column(
            sa.Column(
                "published_revision_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("registration_applicability", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(sa.Column("participant_forms", sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column("major_scope", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("grade_scope", sa.String(length=32), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_competitions_edition_label"), ["edition_label"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competitions_published_revision_id"),
            ["published_revision_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_competitions_series_id"), ["series_id"], unique=False)
        batch_op.create_unique_constraint(
            "uq_competition_series_edition", ["series_id", "edition_label"]
        )
        batch_op.create_foreign_key(
            "fk_competitions_published_revision_id_competition_revisions",
            "competition_revisions",
            ["published_revision_id"],
            ["id"],
            use_alter=True,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_competitions_series_id_competition_series"),
            "competition_series",
            ["series_id"],
            ["id"],
        )

    with op.batch_alter_table("review_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("differences", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("impact", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    if _schema_path() == SCHEMA_PATH_LEGACY:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_records", schema=None) as batch_op:
        batch_op.drop_column("decided_at")
        batch_op.drop_column("submitted_at")
        batch_op.drop_column("impact")
        batch_op.drop_column("differences")

    with op.batch_alter_table("competitions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_competitions_series_id_competition_series"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_competitions_published_revision_id_competition_revisions", type_="foreignkey"
        )
        batch_op.drop_constraint("uq_competition_series_edition", type_="unique")
        batch_op.drop_index(batch_op.f("ix_competitions_series_id"))
        batch_op.drop_index(batch_op.f("ix_competitions_published_revision_id"))
        batch_op.drop_index(batch_op.f("ix_competitions_edition_label"))
        batch_op.drop_column("grade_scope")
        batch_op.drop_column("major_scope")
        batch_op.drop_column("participant_forms")
        batch_op.drop_column("registration_applicability")
        batch_op.drop_column("published_revision_id")
        batch_op.drop_column("edition_label")
        batch_op.drop_column("series_id")

    with op.batch_alter_table("competition_time_nodes", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_competition_time_nodes_stage_id_competition_stages"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_competition_time_nodes_competition_revision_id_competition_revisions"),
            type_="foreignkey",
        )
        batch_op.drop_constraint("uq_competition_revision_node_key", type_="unique")
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_stage_id"))
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_occurs_at"))
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_competition_revision_id"))
        batch_op.alter_column("competition_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("prominence_override_reason")
        batch_op.drop_column("prominence")
        batch_op.drop_column("occurs_at")
        batch_op.drop_column("node_revision")
        batch_op.drop_column("logical_node_key")
        batch_op.drop_column("stage_id")
        batch_op.drop_column("competition_revision_id")

    with op.batch_alter_table("competition_tag_links", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_competition_tag_links_competition_revision_id_competition_revisions"),
            type_="foreignkey",
        )
        batch_op.drop_constraint("uq_competition_revision_tag", type_="unique")
        batch_op.drop_index(batch_op.f("ix_competition_tag_links_competition_revision_id"))
        batch_op.alter_column("competition_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("competition_revision_id")

    op.drop_table("competition_stages")
    with op.batch_alter_table("competition_revisions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_active_competition_revision",
            postgresql_where=sa.text("revision_status IN ('draft', 'pending_review')"),
            sqlite_where=sa.text("revision_status IN ('draft', 'pending_review')"),
        )
        batch_op.drop_index(batch_op.f("ix_competition_revisions_revision_status"))
        batch_op.drop_index(batch_op.f("ix_competition_revisions_published_at"))

    op.drop_table("competition_revisions")
    with op.batch_alter_table("competition_series", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competition_series_canonical_name"))

    op.drop_table("competition_series")
    _drop_postgresql_enum("competition_revision_status")
    # ### end Alembic commands ###


def _schema_path():
    if BASELINE_TABLE not in sa.inspect(op.get_bind()).get_table_names():
        return None
    return (
        op.get_bind()
        .execute(
            sa.text(f"SELECT value FROM {BASELINE_TABLE} WHERE key = :key").bindparams(
                key=BASELINE_KEY
            )
        )
        .scalar()
    )


def _drop_postgresql_enum(enum_name):
    if op.get_bind().dialect.name == "postgresql":
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
