"""add immutable competition revisions

Revision ID: 4a17c3d9e507
Revises:
Create Date: 2026-07-11 15:52:21.691988

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4a17c3d9e507"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competition_tags",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("tag_type", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_tags")),
        sa.UniqueConstraint("code", name=op.f("uq_competition_tags_code")),
    )
    with op.batch_alter_table("competition_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_tags_tag_type"), ["tag_type"], unique=False
        )

    op.create_table(
        "recommendation_rules",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=True),
        sa.Column("reason_template", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_rules")),
        sa.UniqueConstraint("code", name=op.f("uq_recommendation_rules_code")),
    )
    op.create_table(
        "system_configs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_configs")),
        sa.UniqueConstraint("key", name=op.f("uq_system_configs_key")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("student_no", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("student", "admin", "teacher", "organizer", name="user_role"),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("active", "disabled", name="user_status"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
        sa.UniqueConstraint("student_no", name=op.f("uq_users_student_no")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("actor_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column("result", sa.String(length=80), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_logs_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_target_type"), ["target_type"], unique=False
        )

    op.create_table(
        "competition_series",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_competition_series_created_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_series")),
    )
    with op.batch_alter_table("competition_series", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_series_canonical_name"), ["canonical_name"], unique=True
        )

    op.create_table(
        "reminder_settings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("default_remind_days", sa.Integer(), nullable=False),
        sa.Column("node_types", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reminder_settings_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_settings")),
        sa.UniqueConstraint("user_id", name=op.f("uq_reminder_settings_user_id")),
    )
    op.create_table(
        "review_records",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "submitted_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "reviewed_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", "returned", name="review_status"),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("differences", sa.JSON(), nullable=True),
        sa.Column("impact", sa.JSON(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"], ["users.id"], name=op.f("fk_review_records_reviewed_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"], ["users.id"], name=op.f("fk_review_records_submitted_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_records")),
    )
    with op.batch_alter_table("review_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_records_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_review_records_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_review_records_target_type"), ["target_type"], unique=False
        )

    op.create_table(
        "student_profiles",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("college", sa.String(length=120), nullable=True),
        sa.Column("major", sa.String(length=120), nullable=True),
        sa.Column("grade", sa.String(length=40), nullable=True),
        sa.Column("interest_tags", sa.JSON(), nullable=True),
        sa.Column("competition_experience", sa.Text(), nullable=True),
        sa.Column("goal_preferences", sa.JSON(), nullable=True),
        sa.Column("blocked_tags", sa.JSON(), nullable=True),
        sa.Column("default_remind_days", sa.Integer(), nullable=False),
        sa.Column("message_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_student_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_student_profiles_user_id")),
    )
    op.create_table(
        "competitions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("series_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("edition_label", sa.String(length=120), nullable=True),
        sa.Column(
            "published_revision_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("short_title", sa.String(length=120), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("organizer", sa.String(length=255), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("official_url", sa.String(length=1024), nullable=True),
        sa.Column("attachment_url", sa.String(length=1024), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("team_size", sa.String(length=120), nullable=True),
        sa.Column("participant_form", sa.String(length=120), nullable=True),
        sa.Column("suitable_majors", sa.JSON(), nullable=True),
        sa.Column("suitable_grades", sa.JSON(), nullable=True),
        sa.Column("value_notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "unpublished",
                "draft",
                "pending_review",
                "published",
                "rejected",
                "offline",
                "archived",
                "cancelled",
                "expired",
                name="competition_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_competitions_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["competition_series.id"],
            name=op.f("fk_competitions_series_id_competition_series"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitions")),
        sa.UniqueConstraint("series_id", "edition_label", name="uq_competition_series_edition"),
    )
    with op.batch_alter_table("competitions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_competitions_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_competitions_edition_label"), ["edition_label"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competitions_published_revision_id"),
            ["published_revision_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_competitions_series_id"), ["series_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_competitions_short_title"), ["short_title"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_competitions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_competitions_title"), ["title"], unique=False)

    op.create_table(
        "competition_revisions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column(
            "base_revision_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "revision_status",
            sa.Enum(
                "draft",
                "pending_review",
                "approved",
                "rejected",
                "returned",
                name="competition_revision_status",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("short_title", sa.String(length=120), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("organizer", sa.String(length=255), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("official_url", sa.String(length=1024), nullable=True),
        sa.Column("attachment_url", sa.String(length=1024), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("team_size", sa.String(length=120), nullable=True),
        sa.Column("participant_forms", sa.JSON(), nullable=False),
        sa.Column("suitable_majors", sa.JSON(), nullable=True),
        sa.Column("suitable_grades", sa.JSON(), nullable=True),
        sa.Column("value_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "submitted_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_revision_id"],
            ["competition_revisions.id"],
            name=op.f("fk_competition_revisions_base_revision_id_competition_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_competition_revisions_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_competition_revisions_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["users.id"],
            name=op.f("fk_competition_revisions_submitted_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_revisions")),
        sa.UniqueConstraint("competition_id", "revision_number", name="uq_competition_revision"),
    )
    with op.batch_alter_table("competition_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_revisions_revision_status"),
            ["revision_status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_competition_revisions_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(
            "uq_active_competition_revision",
            ["competition_id"],
            unique=True,
            postgresql_where=sa.text("revision_status IN ('draft', 'pending_review')"),
            sqlite_where=sa.text("revision_status IN ('draft', 'pending_review')"),
        )

    with op.batch_alter_table("competitions", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_competitions_published_revision_id_competition_revisions",
            "competition_revisions",
            ["published_revision_id"],
            ["id"],
        )

    op.create_table(
        "favorites",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_favorites_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_favorites_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_favorites")),
    )
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_favorites_competition_id"), ["competition_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_favorites_user_id"), ["user_id"], unique=False)

    op.create_table(
        "subscriptions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("active", "cancelled", "invalid", name="subscription_status"),
            nullable=False,
        ),
        sa.Column("reminder_enabled", sa.Boolean(), nullable=False),
        sa.Column("remind_days", sa.Integer(), nullable=False),
        sa.Column("node_types", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_subscriptions_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_subscriptions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subscriptions_competition_id"), ["competition_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_subscriptions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "competition_stages",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_revision_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("stage_key", sa.String(length=120), nullable=False),
        sa.Column("stage_type", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("stage_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_revision_id"],
            ["competition_revisions.id"],
            name=op.f("fk_competition_stages_competition_revision_id_competition_revisions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_stages")),
        sa.UniqueConstraint(
            "competition_revision_id", "stage_key", name="uq_competition_revision_stage_key"
        ),
        sa.UniqueConstraint(
            "competition_revision_id", "stage_order", name="uq_competition_revision_stage_order"
        ),
    )
    op.create_table(
        "competition_tag_links",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "competition_revision_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("tag_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_competition_tag_links_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["competition_revision_id"],
            ["competition_revisions.id"],
            name=op.f("fk_competition_tag_links_competition_revision_id_competition_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["competition_tags.id"],
            name=op.f("fk_competition_tag_links_tag_id_competition_tags"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_tag_links")),
    )
    with op.batch_alter_table("competition_tag_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_tag_links_competition_revision_id"),
            ["competition_revision_id"],
            unique=False,
        )

    op.create_table(
        "competition_time_nodes",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "competition_revision_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("stage_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("logical_node_key", sa.String(length=120), nullable=True),
        sa.Column("node_revision", sa.Integer(), nullable=False),
        sa.Column("node_type", sa.String(length=80), nullable=False),
        sa.Column("occurs_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("prominence", sa.String(length=20), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_competition_time_nodes_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["competition_revision_id"],
            ["competition_revisions.id"],
            name=op.f("fk_competition_time_nodes_competition_revision_id_competition_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["competition_stages.id"],
            name=op.f("fk_competition_time_nodes_stage_id_competition_stages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_time_nodes")),
        sa.UniqueConstraint(
            "competition_revision_id", "logical_node_key", name="uq_competition_revision_node_key"
        ),
    )
    with op.batch_alter_table("competition_time_nodes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_competition_revision_id"),
            ["competition_revision_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_due_at"), ["due_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_node_type"), ["node_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_occurs_at"), ["occurs_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_stage_id"), ["stage_id"], unique=False
        )

    op.create_table(
        "reminders",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "time_node_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("node_type", sa.String(length=80), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "read", "cancelled", "failed", name="reminder_status"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_reminders_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["time_node_id"],
            ["competition_time_nodes.id"],
            name=op.f("fk_reminders_time_node_id_competition_time_nodes"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reminders_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders")),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reminders_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_reminders_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_reminders_user_id"), ["user_id"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("reminder_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reminder_id"], ["reminders.id"], name=op.f("fk_messages_reminder_id_reminders")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_messages_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_is_read"), ["is_read"], unique=False)
        batch_op.create_index(batch_op.f("ix_messages_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("competitions", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_competitions_published_revision_id_competition_revisions",
            type_="foreignkey",
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_user_id"))
        batch_op.drop_index(batch_op.f("ix_messages_is_read"))

    op.drop_table("messages")
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminders_user_id"))
        batch_op.drop_index(batch_op.f("ix_reminders_status"))
        batch_op.drop_index(batch_op.f("ix_reminders_due_at"))

    op.drop_table("reminders")
    with op.batch_alter_table("competition_time_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_stage_id"))
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_occurs_at"))
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_node_type"))
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_due_at"))
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_competition_revision_id"))

    op.drop_table("competition_time_nodes")
    with op.batch_alter_table("competition_tag_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competition_tag_links_competition_revision_id"))

    op.drop_table("competition_tag_links")
    op.drop_table("competition_stages")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscriptions_user_id"))
        batch_op.drop_index(batch_op.f("ix_subscriptions_competition_id"))

    op.drop_table("subscriptions")
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_favorites_user_id"))
        batch_op.drop_index(batch_op.f("ix_favorites_competition_id"))

    op.drop_table("favorites")
    with op.batch_alter_table("competition_revisions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_active_competition_revision",
            postgresql_where=sa.text("revision_status IN ('draft', 'pending_review')"),
            sqlite_where=sa.text("revision_status IN ('draft', 'pending_review')"),
        )
        batch_op.drop_index(batch_op.f("ix_competition_revisions_published_at"))
        batch_op.drop_index(batch_op.f("ix_competition_revisions_revision_status"))

    op.drop_table("competition_revisions")
    with op.batch_alter_table("competitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competitions_title"))
        batch_op.drop_index(batch_op.f("ix_competitions_status"))
        batch_op.drop_index(batch_op.f("ix_competitions_short_title"))
        batch_op.drop_index(batch_op.f("ix_competitions_series_id"))
        batch_op.drop_index(batch_op.f("ix_competitions_published_revision_id"))
        batch_op.drop_index(batch_op.f("ix_competitions_edition_label"))
        batch_op.drop_index(batch_op.f("ix_competitions_category"))

    op.drop_table("competitions")
    op.drop_table("student_profiles")
    with op.batch_alter_table("review_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_records_target_type"))
        batch_op.drop_index(batch_op.f("ix_review_records_target_id"))
        batch_op.drop_index(batch_op.f("ix_review_records_status"))

    op.drop_table("review_records")
    op.drop_table("reminder_settings")
    with op.batch_alter_table("competition_series", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competition_series_canonical_name"))

    op.drop_table("competition_series")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_target_type"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("system_configs")
    op.drop_table("recommendation_rules")
    with op.batch_alter_table("competition_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competition_tags_tag_type"))

    op.drop_table("competition_tags")
    # ### end Alembic commands ###
