"""initial schema with verified identities

Revision ID: c5e0e7e0560d
Revises:
Create Date: 2026-07-11 13:59:27.573509

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c5e0e7e0560d"
down_revision = None
branch_labels = None
depends_on = None

BASELINE_TABLE = "competehub_migration_baselines"
BASELINE_KEY = "c5e0e7e0560d.schema_path"
SCHEMA_PATH_FRESH = "fresh"
SCHEMA_PATH_LEGACY = "legacy_create_all"


def upgrade():
    if _has_table("users"):
        _record_schema_path(SCHEMA_PATH_LEGACY)
        _upgrade_existing_create_all_schema()
        return
    _record_schema_path(SCHEMA_PATH_FRESH)
    _create_current_schema()


def _create_current_schema():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competition_tags",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("tag_type", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_tags")),
        sa.UniqueConstraint("code", name=op.f("uq_competition_tags_code")),
    )
    with op.batch_alter_table("competition_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_tags_tag_type"), ["tag_type"], unique=False
        )

    op.create_table(
        "recommendation_rules",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=True),
        sa.Column("reason_template", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_rules")),
        sa.UniqueConstraint("code", name=op.f("uq_recommendation_rules_code")),
    )
    op.create_table(
        "system_configs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_configs")),
        sa.UniqueConstraint("key", name=op.f("uq_system_configs_key")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("student_no", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("session_version", sa.Integer(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("student", "admin", "teacher", "organizer", name="user_role"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending_activation", "active", "disabled", name="user_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
        sa.UniqueConstraint("student_no", name=op.f("uq_users_student_no")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("actor_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column("result", sa.String(length=80), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_logs_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_target_type"), ["target_type"], unique=False
        )

    op.create_table(
        "competitions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("short_title", sa.String(length=120), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("organizer", sa.String(length=255), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("official_url", sa.String(length=1024), nullable=True),
        sa.Column("attachment_url", sa.String(length=1024), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("team_size", sa.String(length=120), nullable=True),
        sa.Column("participant_form", sa.String(length=120), nullable=True),
        sa.Column("suitable_majors", sa.JSON(), nullable=True),
        sa.Column("suitable_grades", sa.JSON(), nullable=True),
        sa.Column("value_notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending_review",
                "published",
                "rejected",
                "offline",
                "archived",
                "cancelled",
                "expired",
                name="competition_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_competitions_created_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitions")),
    )
    with op.batch_alter_table("competitions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_competitions_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_competitions_short_title"), ["short_title"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_competitions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_competitions_title"), ["title"], unique=False)

    op.create_table(
        "reminder_settings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("default_remind_days", sa.Integer(), nullable=False),
        sa.Column("node_types", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reminder_settings_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_settings")),
        sa.UniqueConstraint("user_id", name=op.f("uq_reminder_settings_user_id")),
    )
    op.create_table(
        "review_records",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "submitted_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "reviewed_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", "returned", name="review_status"),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"], ["users.id"], name=op.f("fk_review_records_reviewed_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"], ["users.id"], name=op.f("fk_review_records_submitted_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_records")),
    )
    with op.batch_alter_table("review_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_records_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_review_records_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_review_records_target_type"), ["target_type"], unique=False
        )

    op.create_table(
        "student_profiles",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("college", sa.String(length=120), nullable=True),
        sa.Column("major", sa.String(length=120), nullable=True),
        sa.Column("grade", sa.String(length=40), nullable=True),
        sa.Column("interest_tags", sa.JSON(), nullable=True),
        sa.Column("competition_experience", sa.Text(), nullable=True),
        sa.Column("goal_preferences", sa.JSON(), nullable=True),
        sa.Column("blocked_tags", sa.JSON(), nullable=True),
        sa.Column("default_remind_days", sa.Integer(), nullable=False),
        sa.Column("message_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_student_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_student_profiles_user_id")),
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("identity_type", sa.String(length=32), nullable=False),
        sa.Column("normalized_value", sa.String(length=255), nullable=False),
        sa.Column("display_value", sa.String(length=255), nullable=False),
        sa.Column(
            "verification_status",
            sa.Enum("pending", "verified", name="identity_verification_status"),
            nullable=False,
        ),
        sa.Column("verification_method", sa.String(length=64), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_identities_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identities")),
        sa.UniqueConstraint("identity_type", "normalized_value", name="uq_identity_type_value"),
    )
    op.create_table(
        "competition_tag_links",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("tag_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_competition_tag_links_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["competition_tags.id"],
            name=op.f("fk_competition_tag_links_tag_id_competition_tags"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_tag_links")),
    )
    op.create_table(
        "competition_time_nodes",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("node_type", sa.String(length=80), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_competition_time_nodes_competition_id_competitions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_time_nodes")),
    )
    with op.batch_alter_table("competition_time_nodes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_due_at"), ["due_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_time_nodes_node_type"), ["node_type"], unique=False
        )

    op.create_table(
        "favorites",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_favorites_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_favorites_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_favorites")),
    )
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_favorites_competition_id"), ["competition_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_favorites_user_id"), ["user_id"], unique=False)

    op.create_table(
        "identity_verification_challenges",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "user_identity_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("secret_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_identity_id"],
            ["user_identities.id"],
            name=op.f("fk_identity_verification_challenges_user_identity_id_user_identities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_verification_challenges")),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("active", "cancelled", "invalid", name="subscription_status"),
            nullable=False,
        ),
        sa.Column("reminder_enabled", sa.Boolean(), nullable=False),
        sa.Column("remind_days", sa.Integer(), nullable=False),
        sa.Column("node_types", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_subscriptions_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_subscriptions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subscriptions_competition_id"), ["competition_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_subscriptions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "reminders",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "competition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "time_node_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("node_type", sa.String(length=80), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "read", "cancelled", "failed", name="reminder_status"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_reminders_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["time_node_id"],
            ["competition_time_nodes.id"],
            name=op.f("fk_reminders_time_node_id_competition_time_nodes"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reminders_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders")),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reminders_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_reminders_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_reminders_user_id"), ["user_id"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("reminder_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reminder_id"], ["reminders.id"], name=op.f("fk_messages_reminder_id_reminders")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_messages_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_is_read"), ["is_read"], unique=False)
        batch_op.create_index(batch_op.f("ix_messages_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def _upgrade_existing_create_all_schema():
    _add_pending_activation_enum_value()
    if not _has_column("users", "session_version"):
        with op.batch_alter_table("users", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column("session_version", sa.Integer(), nullable=False, server_default="1")
            )
    if not _has_column("users", "capabilities"):
        with op.batch_alter_table("users", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "capabilities",
                    sa.JSON(),
                    nullable=False,
                    server_default=_json_empty_array_default(),
                )
            )
    if not _has_table("user_identities"):
        _create_user_identities_table()
    if not _has_table("identity_verification_challenges"):
        _create_identity_verification_challenges_table()
    _backfill_user_identities()


def _create_user_identities_table():
    op.create_table(
        "user_identities",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("identity_type", sa.String(length=32), nullable=False),
        sa.Column("normalized_value", sa.String(length=255), nullable=False),
        sa.Column("display_value", sa.String(length=255), nullable=False),
        sa.Column(
            "verification_status",
            sa.Enum("pending", "verified", name="identity_verification_status"),
            nullable=False,
        ),
        sa.Column("verification_method", sa.String(length=64), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_identities_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identities")),
        sa.UniqueConstraint("identity_type", "normalized_value", name="uq_identity_type_value"),
    )


def _create_identity_verification_challenges_table():
    op.create_table(
        "identity_verification_challenges",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "user_identity_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("secret_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_identity_id"],
            ["user_identities.id"],
            name=op.f("fk_identity_verification_challenges_user_identity_id_user_identities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_verification_challenges")),
    )


def _backfill_user_identities():
    _backfill_identity("email", "LOWER(TRIM(users.email))", "LOWER(TRIM(candidate.email))", "email")
    _backfill_identity("phone", "TRIM(users.phone)", "TRIM(candidate.phone)", "phone")
    _backfill_identity(
        "student_no",
        "TRIM(users.student_no)",
        "TRIM(candidate.student_no)",
        "student_no",
    )


def _backfill_identity(identity_type, normalized_expression, candidate_expression, display_column):
    op.execute(
        sa.text(
            f"""
            INSERT INTO user_identities (
                user_id,
                identity_type,
                normalized_value,
                display_value,
                verification_status,
                verification_method,
                verified_at,
                created_at,
                updated_at
            )
            SELECT
                users.id,
                :identity_type,
                {normalized_expression},
                users.{display_column},
                'verified',
                'legacy_backfill',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            FROM users
            WHERE users.{display_column} IS NOT NULL
              AND TRIM(users.{display_column}) != ''
              AND users.id = (
                  SELECT MIN(candidate.id)
                  FROM users AS candidate
                  WHERE candidate.{display_column} IS NOT NULL
                    AND TRIM(candidate.{display_column}) != ''
                    AND {candidate_expression} = {normalized_expression}
              )
              AND NOT EXISTS (
                  SELECT 1
                  FROM user_identities
                  WHERE user_identities.identity_type = :identity_type
                    AND user_identities.normalized_value = {normalized_expression}
              )
            """
        ).bindparams(identity_type=identity_type)
    )


def _add_pending_activation_enum_value():
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE user_status ADD VALUE IF NOT EXISTS 'pending_activation'")


def _json_empty_array_default():
    if op.get_bind().dialect.name == "postgresql":
        return sa.text("'[]'::json")
    return sa.text("'[]'")


def _record_schema_path(path):
    if not _has_table(BASELINE_TABLE):
        op.create_table(
            BASELINE_TABLE,
            sa.Column("key", sa.String(length=120), nullable=False),
            sa.Column("value", sa.String(length=120), nullable=False),
            sa.PrimaryKeyConstraint("key", name=op.f(f"pk_{BASELINE_TABLE}")),
        )
    op.execute(
        sa.text(f"DELETE FROM {BASELINE_TABLE} WHERE key = :key").bindparams(key=BASELINE_KEY)
    )
    op.execute(
        sa.text(f"INSERT INTO {BASELINE_TABLE} (key, value) VALUES (:key, :value)").bindparams(
            key=BASELINE_KEY, value=path
        )
    )


def _schema_path():
    if not _has_table(BASELINE_TABLE):
        return None
    return (
        op.get_bind()
        .execute(
            sa.text(f"SELECT value FROM {BASELINE_TABLE} WHERE key = :key").bindparams(
                key=BASELINE_KEY
            )
        )
        .scalar()
    )


def _drop_baseline_table():
    if _has_table(BASELINE_TABLE):
        op.drop_table(BASELINE_TABLE)


def _has_table(table_name):
    return table_name in sa.inspect(op.get_bind()).get_table_names()


def _has_column(table_name, column_name):
    if not _has_table(table_name):
        return False
    return any(
        column["name"] == column_name
        for column in sa.inspect(op.get_bind()).get_columns(table_name)
    )


def downgrade():
    schema_path = _schema_path()
    if schema_path == SCHEMA_PATH_LEGACY or (schema_path is None and _has_table("users")):
        _downgrade_existing_create_all_schema()
        return
    _downgrade_fresh_schema()


def _downgrade_existing_create_all_schema():
    if _has_table("identity_verification_challenges"):
        op.drop_table("identity_verification_challenges")
    if _has_table("user_identities"):
        op.drop_table("user_identities")
    columns_to_drop = [
        column_name
        for column_name in ("session_version", "capabilities")
        if _has_column("users", column_name)
    ]
    if columns_to_drop:
        with op.batch_alter_table("users", schema=None) as batch_op:
            for column_name in columns_to_drop:
                batch_op.drop_column(column_name)
    _drop_baseline_table()


def _downgrade_fresh_schema():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_user_id"))
        batch_op.drop_index(batch_op.f("ix_messages_is_read"))

    op.drop_table("messages")
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminders_user_id"))
        batch_op.drop_index(batch_op.f("ix_reminders_status"))
        batch_op.drop_index(batch_op.f("ix_reminders_due_at"))

    op.drop_table("reminders")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscriptions_user_id"))
        batch_op.drop_index(batch_op.f("ix_subscriptions_competition_id"))

    op.drop_table("subscriptions")
    op.drop_table("identity_verification_challenges")
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_favorites_user_id"))
        batch_op.drop_index(batch_op.f("ix_favorites_competition_id"))

    op.drop_table("favorites")
    with op.batch_alter_table("competition_time_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_node_type"))
        batch_op.drop_index(batch_op.f("ix_competition_time_nodes_due_at"))

    op.drop_table("competition_time_nodes")
    op.drop_table("competition_tag_links")
    op.drop_table("user_identities")
    op.drop_table("student_profiles")
    with op.batch_alter_table("review_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_records_target_type"))
        batch_op.drop_index(batch_op.f("ix_review_records_target_id"))
        batch_op.drop_index(batch_op.f("ix_review_records_status"))

    op.drop_table("review_records")
    op.drop_table("reminder_settings")
    with op.batch_alter_table("competitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competitions_title"))
        batch_op.drop_index(batch_op.f("ix_competitions_status"))
        batch_op.drop_index(batch_op.f("ix_competitions_short_title"))
        batch_op.drop_index(batch_op.f("ix_competitions_category"))

    op.drop_table("competitions")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_target_type"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("system_configs")
    op.drop_table("recommendation_rules")
    with op.batch_alter_table("competition_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competition_tags_tag_type"))

    op.drop_table("competition_tags")
    _drop_baseline_table()
    # ### end Alembic commands ###
