"""Competition catalog data extracted from Beijing University of Technology 2023 undergraduate competition recognition PDFs."""

CATALOG_ITEMS = [{'catalog_level': 'A', 'number': 1, 'name': '中国国际“互联网+”大学生创新创业大赛竞赛', 'code': 'A2428101'},
 {'catalog_level': 'A', 'number': 2, 'name': '“挑战杯”全国大学生课外学术科技作品竞赛', 'code': 'A2422102'},
 {'catalog_level': 'A', 'number': 3, 'name': '“挑战杯”中国大学生创业计划竞赛', 'code': 'A2026103'},
 {'catalog_level': 'A', 'number': 4, 'name': 'ACM—ICPC国际大学生程序设计竞赛', 'code': 'A1011104'},
 {'catalog_level': 'A', 'number': 5, 'name': '华为ICT大赛', 'code': 'A1217005'},
 {'catalog_level': 'A', 'number': 6, 'name': '全国大学生机械创新设计大赛', 'code': 'A2110106'},
 {'catalog_level': 'A', 'number': 7, 'name': '中国大学生工程实践与创新能力大赛', 'code': 'A2319107'},
 {'catalog_level': 'A', 'number': 8, 'name': '全国大学生先进成图技术与产品信息建模创新大赛', 'code': 'A2010108'},
 {'catalog_level': 'A', 'number': 9, 'name': '全国三维数字化创新设计大赛', 'code': 'A2016109'},
 {'catalog_level': 'A', 'number': 10, 'name': '全国大学生金相技能大赛', 'code': 'A2215110'},
 {'catalog_level': 'A', 'number': 11, 'name': '全国周培源大学生力学竞赛', 'code': 'A2018111'},
 {'catalog_level': 'A', 'number': 12, 'name': '中国大学生机械工程创新创意大赛', 'code': 'A2817112'},
 {'catalog_level': 'A', 'number': 13, 'name': '全国大学生结构设计竞赛', 'code': 'A2010113'},
 {'catalog_level': 'A', 'number': 14, 'name': '全国大学生电子商务“创新、创意及创业”挑战赛', 'code': 'A2213114'},
 {'catalog_level': 'A', 'number': 15, 'name': '全国大学生化工设计竞赛', 'code': 'A2014115'},
 {'catalog_level': 'A', 'number': 16, 'name': '全国大学生节能减排社会实践与科技竞赛', 'code': 'A2215016'},
 {'catalog_level': 'A', 'number': 17, 'name': '全国大学生化学实验创新设计大赛', 'code': 'A2016117'},
 {'catalog_level': 'A', 'number': 18, 'name': '全国大学生化工实验大赛', 'code': 'A2017118'},
 {'catalog_level': 'A', 'number': 19, 'name': '全国大学生市场调查与分析大赛', 'code': 'A2010119'},
 {'catalog_level': 'A', 'number': 20, 'name': '全国大学生能源经济学术创意大赛', 'code': 'A2418120'},
 {'catalog_level': 'A', 'number': 21, 'name': '全国大学生数学建模竞赛', 'code': 'A2014121'},
 {'catalog_level': 'A', 'number': 22, 'name': '全国大学生光电设计竞赛', 'code': 'A2010122'},
 {'catalog_level': 'A', 'number': 23, 'name': '全国大学生物理实验竞赛', 'code': 'A2011023'},
 {'catalog_level': 'A', 'number': 24, 'name': '全国大学生统计建模大赛', 'code': 'A2112124'},
 {'catalog_level': 'A', 'number': 25, 'name': '外研社全国大学生英语系列赛1', 'code': 'A2213125'},
 {'catalog_level': 'A', 'number': 26, 'name': '“外研社杯”全国高校学生跨文化能力大赛', 'code': 'A2013026'},
 {'catalog_level': 'A', 'number': 27, 'name': '全国大学生创新创业年会', 'code': 'A2015027'},
 {'catalog_level': 'A', 'number': 28, 'name': '中国大学生服务外包创新创业大赛', 'code': 'A2218128'},
 {'catalog_level': 'A', 'number': 29, 'name': '全国大学生电子设计竞赛', 'code': 'A2218129'},
 {'catalog_level': 'A', 'number': 30, 'name': '全国大学生智能汽车竞赛', 'code': 'A2010130'},
 {'catalog_level': 'A', 'number': 31, 'name': '全国大学生机器人大赛—RoboMaster、RoboCon', 'code': 'A2114131'},
 {'catalog_level': 'A', 'number': 32, 'name': '“西门子杯”中国智能制造挑战赛', 'code': 'A2011132'},
 {'catalog_level': 'A', 'number': 33, 'name': '中国高校计算机大赛', 'code': 'A2410133'},
 {'catalog_level': 'A', 'number': 34, 'name': '全国大学生集成电路创新创业大赛', 'code': 'A2018134'},
 {'catalog_level': 'A', 'number': 35, 'name': '全国大学生信息安全竞赛', 'code': 'A2213035'},
 {'catalog_level': 'A', 'number': 36, 'name': '中国机器人大赛暨RoboCup机器人世界杯中国赛', 'code': 'A2012036'},
 {'catalog_level': 'A', 'number': 37, 'name': '“中国软件杯”大学生软件设计大赛', 'code': 'A2510137'},
 {'catalog_level': 'A', 'number': 38, 'name': '全国大学生嵌入式芯片与系统设计竞赛', 'code': 'A2210138'},
 {'catalog_level': 'A', 'number': 39, 'name': '睿抗机器人开发者大赛（RAIC0M）', 'code': 'A2410139'},
 {'catalog_level': 'A', 'number': 40, 'name': '“大唐杯”全国大学生新一代信息通信技术大赛', 'code': 'A2217140'},
 {'catalog_level': 'A', 'number': 41, 'name': '中国高校智能机器人创意大赛', 'code': 'A2215141'},
 {'catalog_level': 'A', 'number': 42, 'name': '中国好创意暨全国数字艺术设计大赛', 'code': 'A2013042'},
 {'catalog_level': 'A', 'number': 43, 'name': '中国机器人及人工智能大赛', 'code': 'A2010143'},
 {'catalog_level': 'A', 'number': 44, 'name': 'iCAN大学生创新创业大赛', 'code': 'A2112144'},
 {'catalog_level': 'A', 'number': 45, 'name': '全国大学生物联网设计竞赛', 'code': 'A2015145'},
 {'catalog_level': 'A', 'number': 46, 'name': '全国大学生数字媒体科技作品及创意竞赛', 'code': 'A2017046'},
 {'catalog_level': 'A', 'number': 47, 'name': '全国大学生广告艺术大赛', 'code': 'A2016147'},
 {'catalog_level': 'A', 'number': 48, 'name': '两岸新锐设计竞赛.华灿奖', 'code': 'A2016148'},
 {'catalog_level': 'A', 'number': 49, 'name': '未来设计师.全国高校数字艺术设计大赛', 'code': 'A2210149'},
 {'catalog_level': 'A', 'number': 50, 'name': '中国大学生计算机设计大赛', 'code': 'A2010150'},
 {'catalog_level': 'A', 'number': 51, 'name': '“蓝桥杯”全国软件和信息技术专业人才大赛', 'code': 'A3808151'},
 {'catalog_level': 'A', 'number': 52, 'name': '米兰设计周——中国高校设计学科师生优秀作品展', 'code': 'A3008152'},
 {'catalog_level': 'A', 'number': 53, 'name': '外研社全国大学生英语系列赛2', 'code': 'A3202053'},
 {'catalog_level': 'A', 'number': 54, 'name': '全国大学生水利创新设计大赛', 'code': 'A3008054'},
 {'catalog_level': 'A', 'number': 55, 'name': '北京市大学生交通科技大赛', 'code': 'A3013055'},
 {'catalog_level': 'A', 'number': 56, 'name': '“京彩大创”北京大学生创新创业大赛', 'code': 'A3516056'},
 {'catalog_level': 'A', 'number': 57, 'name': '北京市大学生节能节水低碳减排社会实践与科技竞赛', 'code': 'A3212057'},
 {'catalog_level': 'A', 'number': 58, 'name': '北京市大学生生物学竞赛', 'code': 'A3310058'},
 {'catalog_level': 'A', 'number': 59, 'name': '北京市大学生化学实验竞赛', 'code': 'A3010059'},
 {'catalog_level': 'A', 'number': 60, 'name': '北京市大学生化工原理竞赛', 'code': 'A3015060'},
 {'catalog_level': 'A', 'number': 61, 'name': '北京市大学生物理实验竞赛', 'code': 'A3016061'},
 {'catalog_level': 'A', 'number': 62, 'name': '北京市大学生人文知识竞赛', 'code': 'A3019062'},
 {'catalog_level': 'A', 'number': 63, 'name': '北京市大学生模拟法庭竞赛', 'code': 'A3014063'},
 {'catalog_level': 'A', 'number': 64, 'name': '北京市大学生英语演讲比赛', 'code': 'A3018064'},
 {'catalog_level': 'A', 'number': 65, 'name': '北京市大学生“用外语讲好中国故事”优秀短视频 作品征集活动', 'code': 'A3018065'},
 {'catalog_level': 'A', 'number': 66, 'name': '"外研社▪词达人杯"全国大学生英语词汇能力大赛- 北京赛区', 'code': 'A3017066'},
 {'catalog_level': 'A', 'number': 67, 'name': '北京市大学生动漫设计竞赛', 'code': 'A3016067'},
 {'catalog_level': 'A', 'number': 68, 'name': '华北五省（市、自治区）大学生机器人大赛', 'code': 'A3010068'},
 {'catalog_level': 'A', 'number': 69, 'name': '北京市大学生电子设计竞赛', 'code': 'A3012069'},
 {'catalog_level': 'A', 'number': 70, 'name': '北京市大学生集成电路设计大赛', 'code': 'A3013070'},
 {'catalog_level': 'A', 'number': 71, 'name': '北京市大学生文创设计大赛', 'code': 'A3015071'},
 {'catalog_level': 'A', 'number': 72, 'name': '北京市大学生工业设计大赛', 'code': 'A3018072'},
 {'catalog_level': 'B', 'number': 1, 'name': '全国学生（青年）运动会及全国大学生单项体育竞赛', 'code': 'B2012001'},
 {'catalog_level': 'B', 'number': 2, 'name': '全国大学生数学竞赛', 'code': 'C2212132'},
 {'catalog_level': 'B', 'number': 3, 'name': '全国部分地区大学生物理竞赛', 'code': 'C3312038'},
 {'catalog_level': 'B', 'number': 4, 'name': '全国大学生可再生能源优秀科技作品竞赛', 'code': 'B2012002'},
 {'catalog_level': 'B', 'number': 5, 'name': 'WUPENiCITY 城市可持续调研报告国际竞赛和 WUPENiCITY 城市设计学生作业国际竞赛', 'code': 'C1012003'},
 {'catalog_level': 'B', 'number': 6, 'name': '亚洲设计学年奖', 'code': 'B1112003'},
 {'catalog_level': 'B', 'number': 7, 'name': '美国大学生数学建模竞赛', 'code': 'C1012005'},
 {'catalog_level': 'B', 'number': 8, 'name': 'IEEE Xtreme 极限编程全球大赛', 'code': 'C1012006'},
 {'catalog_level': 'B', 'number': 9, 'name': '全国大学生电装技术创新大赛', 'code': 'B2012004'},
 {'catalog_level': 'B', 'number': 10, 'name': '全国大学生结构设计信息技术大赛', 'code': 'B2012005'},
 {'catalog_level': 'B', 'number': 11, 'name': '“共创杯”智能建造技术创新大赛', 'code': 'B2012006'},
 {'catalog_level': 'B', 'number': 12, 'name': '“深水杯”全国大学生给排水科技创新大赛', 'code': 'C2212011'},
 {'catalog_level': 'B', 'number': 13, 'name': '人工环境工程学科奖学金', 'code': 'C2012012'},
 {'catalog_level': 'B', 'number': 14, 'name': '全国大学生交通科技大赛', 'code': 'C2112014'},
 {'catalog_level': 'B', 'number': 15, 'name': '全国大学生生物医学工程创新设计竞赛', 'code': 'C2212018'},
 {'catalog_level': 'B', 'number': 16, 'name': '中国制冷空调行业大学生科技竞赛', 'code': 'C2012117'},
 {'catalog_level': 'B', 'number': 17, 'name': '全国高等院校企业竞争模拟大赛', 'code': 'C2212019'},
 {'catalog_level': 'B', 'number': 18, 'name': '香港会计师公会商业个案比赛', 'code': 'C2012020'},
 {'catalog_level': 'B', 'number': 19, 'name': '“创青春”中国青年创新创业大赛', 'code': 'C2412026'},
 {'catalog_level': 'B', 'number': 20, 'name': '全国大学生英语竞赛', 'code': 'C2012122'},
 {'catalog_level': 'B', 'number': 21, 'name': '中国工程机器人大赛暨国际公开赛', 'code': 'B2512107'},
 {'catalog_level': 'B', 'number': 22, 'name': '“博创杯”全国大学生嵌入式人工智能设计大赛', 'code': 'C2012131'},
 {'catalog_level': 'B', 'number': 23, 'name': '中国（国际）传感器创新创业大赛', 'code': 'B2212008'},
 {'catalog_level': 'B', 'number': 24, 'name': '开源创新大赛', 'code': 'C2412027'},
 {'catalog_level': 'B', 'number': 25, 'name': '国际自主智能机器人大赛', 'code': 'C2412028'},
 {'catalog_level': 'B', 'number': 26, 'name': '全国大学生美术作品展', 'code': 'B2012009'},
 {'catalog_level': 'B', 'number': 27, 'name': '北京市大学生物理学术竞赛', 'code': 'C3012037'},
 {'catalog_level': 'B', 'number': 28, 'name': '全国大学生市政环境类创新实践能力大赛', 'code': 'C3212136'},
 {'catalog_level': 'B', 'number': 29, 'name': '中国社会工作大学生论坛', 'code': 'C3012039'},
 {'catalog_level': 'B', 'number': 30, 'name': '"强东杯"高校社会学知识竞赛', 'code': 'C3012040'},
 {'catalog_level': 'B', 'number': 31, 'name': '全国大学生软件创新大赛', 'code': 'C3012041'},
 {'catalog_level': 'B', 'number': 32, 'name': '时报金犊奖', 'code': 'C3312042'},
 {'catalog_level': 'C', 'number': 1, 'name': 'UIA-霍普杯”国际大学生建筑设计竞赛', 'code': 'C1012001'},
 {'catalog_level': 'C', 'number': 2, 'name': 'CAR-ASHRAE学生设计竞赛', 'code': 'C1012002'},
 {'catalog_level': 'C', 'number': 3, 'name': 'WUPENiCITY 城市可持续调研报告国际竞赛 和WUPENiCITY 城市设计学生作业国际竞赛', 'code': 'C1012003'},
 {'catalog_level': 'C', 'number': 4, 'name': '国际大学生混凝土龙舟邀请赛', 'code': 'C1112004'},
 {'catalog_level': 'C', 'number': 5, 'name': '美国大学生数学建模竞赛', 'code': 'C1012005'},
 {'catalog_level': 'C', 'number': 6, 'name': 'IEEE Xtreme 极限编程全球大赛', 'code': 'C1012006'},
 {'catalog_level': 'C', 'number': 7, 'name': 'SAMPE 超轻复合材料机翼/桥梁学生竞赛', 'code': 'C2012007'},
 {'catalog_level': 'C', 'number': 8, 'name': '一带一路暨金砖国家技能发展与技术创新大赛', 'code': 'C2112008'},
 {'catalog_level': 'C', 'number': 9, 'name': '全国高校学生钢结构创新竞赛', 'code': 'C2012009'},
 {'catalog_level': 'C', 'number': 10, 'name': '“谷雨杯”全国大学生可持续建筑设计竞赛', 'code': 'C2012010'},
 {'catalog_level': 'C', 'number': 11, 'name': '“深水杯”全国大学生给排水科技创新大赛', 'code': 'C2212011'},
 {'catalog_level': 'C', 'number': 12, 'name': '人工环境工程学科奖学金', 'code': 'C2012012'},
 {'catalog_level': 'C', 'number': 13, 'name': '全国高校智能交通创新与创业大赛', 'code': 'C2112013'},
 {'catalog_level': 'C', 'number': 14, 'name': '全国大学生交通科技大赛', 'code': 'C2112014'},
 {'catalog_level': 'C', 'number': 15, 'name': '全国大学生国土空间规划设计竞赛', 'code': 'C2012015'},
 {'catalog_level': 'C', 'number': 16, 'name': '全国大学生“茅以升公益桥——小桥工程” 设计大赛', 'code': 'C2012016'},
 {'catalog_level': 'C', 'number': 17, 'name': '中国制冷空调行业大学生科技竞赛', 'code': 'C2012117'},
 {'catalog_level': 'C', 'number': 18, 'name': '全国大学生生物医学工程创新设计竞赛', 'code': 'C2212018'},
 {'catalog_level': 'C', 'number': 19, 'name': '全国高等院校企业竞争模拟大赛', 'code': 'C2212019'},
 {'catalog_level': 'C', 'number': 20, 'name': '香港会计师公会商业个案比赛', 'code': 'C2012020'},
 {'catalog_level': 'C', 'number': 21, 'name': '全国高校大学日语演讲比赛', 'code': 'C2012021'},
 {'catalog_level': 'C', 'number': 22, 'name': '全国大学生英语竞赛', 'code': 'C2012122'},
 {'catalog_level': 'C', 'number': 23, 'name': '中国大学生广告艺术节学院奖', 'code': 'C2212023'},
 {'catalog_level': 'C', 'number': 24, 'name': '全国青年科普创新实验暨作品大赛', 'code': 'C2012124'},
 {'catalog_level': 'C', 'number': 25, 'name': '全国科学实验展演汇演活动', 'code': 'C2012125'},
 {'catalog_level': 'C', 'number': 26, 'name': '“创青春”中国青年创新创业大赛', 'code': 'C2412026'},
 {'catalog_level': 'C', 'number': 27, 'name': '开源创新大赛', 'code': 'C2412027'},
 {'catalog_level': 'C', 'number': 28, 'name': '国际自主智能机器人大赛', 'code': 'C2412028'},
 {'catalog_level': 'C', 'number': 29, 'name': 'IET 全球科技英语演讲竞赛IET Present Around The World', 'code': 'C2012029'},
 {'catalog_level': 'C', 'number': 30, 'name': '中国大学生计算机博弈大赛', 'code': 'C2012130'},
 {'catalog_level': 'C', 'number': 31, 'name': '“博创杯”全国大学生嵌入式人工智能设计 大赛', 'code': 'C2012131'},
 {'catalog_level': 'C', 'number': 32, 'name': '全国大学生数学竞赛', 'code': 'C2212132'},
 {'catalog_level': 'C', 'number': 33, 'name': '全国大学生焊接创新大赛', 'code': 'C3012033'},
 {'catalog_level': 'C', 'number': 34, 'name': '北京市测绘技能大赛', 'code': 'C3112034'},
 {'catalog_level': 'C', 'number': 35, 'name': '“龙图杯”全国BIM大赛', 'code': 'C3112035'},
 {'catalog_level': 'C', 'number': 36, 'name': '全国大学生市政环境类创新实践能力大赛', 'code': 'C3212136'},
 {'catalog_level': 'C', 'number': 37, 'name': '北京市大学生物理学术竞赛', 'code': 'C3012037'},
 {'catalog_level': 'C', 'number': 38, 'name': '全国部分地区大学生物理竞赛', 'code': 'C3312038'},
 {'catalog_level': 'C', 'number': 39, 'name': '中国社会工作大学生论坛', 'code': 'C3012039'},
 {'catalog_level': 'C', 'number': 40, 'name': '"强东杯"高校社会学知识竞赛', 'code': 'C3012040'},
 {'catalog_level': 'C', 'number': 41, 'name': '全国大学生软件创新大赛', 'code': 'C3012041'},
 {'catalog_level': 'C', 'number': 42, 'name': '时报金犊奖', 'code': 'C3312042'},
 {'catalog_level': 'C', 'number': 43, 'name': '中国大学生工程实践与创新能力大赛校选赛', 'code': 'C4012043'},
 {'catalog_level': 'C', 'number': 44, 'name': '北京工业大学金相技能大赛', 'code': 'C4012044'},
 {'catalog_level': 'C', 'number': 45, 'name': '北京工业大学给排水科技创新大赛', 'code': 'C4212045'},
 {'catalog_level': 'C', 'number': 46, 'name': '北京工业大学交通科技竞赛', 'code': 'C4012046'},
 {'catalog_level': 'C', 'number': 47, 'name': '北京工业大学结构设计大赛', 'code': 'C4412047'},
 {'catalog_level': 'C', 'number': 48, 'name': '北京工业大学水利创新设计竞赛', 'code': 'C4012048'},
 {'catalog_level': 'C', 'number': 49, 'name': '北京工业大学空间形态设计大赛', 'code': 'C4012049'},
 {'catalog_level': 'C', 'number': 50, 'name': '北京工业大学“未来之星”职业生涯规划大赛', 'code': 'C4012050'},
 {'catalog_level': 'C', 'number': 51, 'name': '北京工业大学节能减排社会实践与科技竞赛', 'code': 'C4012051'},
 {'catalog_level': 'C', 'number': 52, 'name': '北京工业大学化学实验竞赛', 'code': 'C4012052'},
 {'catalog_level': 'C', 'number': 53, 'name': '北京工业大学《化工原理》课程竞赛', 'code': 'C4012053'},
 {'catalog_level': 'C', 'number': 54, 'name': '北京工业大学CASIO杯物理知识竞赛', 'code': 'C4012054'},
 {'catalog_level': 'C', 'number': 55, 'name': '北京工业大学物理实验设计竞赛', 'code': 'C4012055'},
 {'catalog_level': 'C', 'number': 56, 'name': '北京工业大学中华经典美文诵读大赛', 'code': 'C4012056'},
 {'catalog_level': 'C', 'number': 57, 'name': '全国大学生学术英语词汇竞赛', 'code': 'C4012057'},
 {'catalog_level': 'C', 'number': 58, 'name': '北京工业大学模拟法庭竞赛', 'code': 'C4012058'},
 {'catalog_level': 'C', 'number': 59, 'name': '北京工业大学人文知识竞赛', 'code': 'C4012059'},
 {'catalog_level': 'C', 'number': 60, 'name': '“外研社杯”英语（辩论、演讲、写作、阅 读）赛校内选拔赛', 'code': 'C4012060'},
 {'catalog_level': 'C', 'number': 61, 'name': '北京工业大学“鼎新杯”学生创意创新创业 竞赛', 'code': 'C4012061'},
 {'catalog_level': 'C', 'number': 62, 'name': '北京工业大学电子设计竞赛', 'code': 'C4012062'},
 {'catalog_level': 'C', 'number': 63, 'name': '北京工业大学嵌入式系统竞赛', 'code': 'C4012063'},
 {'catalog_level': 'C', 'number': 64, 'name': '北京工业大学智能车选拔赛', 'code': 'C4012064'},
 {'catalog_level': 'C', 'number': 65, 'name': '北京工业大学机器人赛', 'code': 'C4012065'},
 {'catalog_level': 'C', 'number': 66, 'name': '北京工业大学计算机博弈大赛', 'code': 'C4012066'},
 {'catalog_level': 'C', 'number': 67, 'name': 'IET全球科技英语演讲竞赛校内赛', 'code': 'C4012067'},
 {'catalog_level': 'C', 'number': 68, 'name': '全国大学生物联网设计竞赛校内选拔赛', 'code': 'C4012068'},
 {'catalog_level': 'C', 'number': 69, 'name': 'ACM国际大学生程序设计竞赛校内选拔赛', 'code': 'C4012069'},
 {'catalog_level': 'C', 'number': 70, 'name': '中国高校计算机大赛网络技术挑战赛校内选拔赛', 'code': 'C4012070'},
 {'catalog_level': 'C', 'number': 71, 'name': '北京工业大学iCAN大赛', 'code': 'C4112071'},
 {'catalog_level': 'C', 'number': 72, 'name': '"蓝桥杯"全国软件和信息技术专业人才大赛 暨“中国高校计算机大赛-团队程序天梯赛” 校内预选赛', 'code': 'C4012072'},
 {'catalog_level': 'C', 'number': 73, 'name': '华为ICT大赛校内选拔赛', 'code': 'C4112073'},
 {'catalog_level': 'C', 'number': 74, 'name': '北京工业大学数学建模竞赛', 'code': 'C4012074'},
 {'catalog_level': 'C', 'number': 75, 'name': '北京工业大学制冷空调科技竞赛', 'code': 'C4012075'},
 {'catalog_level': 'C', 'number': 76, 'name': '北京工业大学学生教学技能大赛', 'code': 'C4012076'},
 {'catalog_level': 'D', 'number': 1, 'name': '“工大杯”工程制作创新赛', 'code': 'D4012001'},
 {'catalog_level': 'D', 'number': 2, 'name': '“工大杯”程序设计大赛', 'code': 'D4012002'},
 {'catalog_level': 'D', 'number': 3, 'name': '“工大杯”电路与电子设计竞赛', 'code': 'D4012003'},
 {'catalog_level': 'D', 'number': 4, 'name': '“工大杯”物理实验竞赛', 'code': 'D4012004'},
 {'catalog_level': 'D', 'number': 5, 'name': '“工大杯”电子封装技术大赛', 'code': 'D4012005'},
 {'catalog_level': 'D', 'number': 6, 'name': '“工大杯”大学生科研英语演讲比赛', 'code': 'D4012006'}]

OFFICIAL_INFO = {'中国国际“互联网+”大学生创新创业大赛竞赛': {'url': 'https://cy.ncss.cn/',
                           'timeline': '报名启动后，通常 4-7 月参赛报名，4-8 月高校初赛和省市复赛，9 月总决赛；以全国大学生创业服务网当年通知为准。'},
 '“挑战杯”全国大学生课外学术科技作品竞赛': {'url': 'https://www.tiaozhanbei.net/',
                          'timeline': '挑战杯两个并列项目交替举办，一般经历校赛、省赛、国赛；以挑战杯官网当年赛季通知为准。'},
 '“挑战杯”中国大学生创业计划竞赛': {'url': 'https://www.tiaozhanbei.net/', 'timeline': '挑战杯创业计划竞赛与课外学术科技作品竞赛交替举办；以挑战杯官网当年赛季通知为准。'},
 'ACM—ICPC国际大学生程序设计竞赛': {'url': 'https://icpc.global/', 'timeline': '区域赛通常在秋季集中进行，报名和站点安排以 ICPC 官方与各区域站通知为准。'},
 '华为ICT大赛': {'url': 'https://e.huawei.com/cn/talent/ict-academy/#/ict-contest',
             'timeline': '通常包含校赛/省赛/全国赛/全球赛，报名和考试安排以华为 ICT 大赛当季通知为准。'},
 '全国大学生数学建模竞赛': {'url': 'https://www.mcm.edu.cn/',
                 'timeline': '2026 年赛题发布时间为 2026-09-10 18:00；报名和论文提交以全国大学生数学建模竞赛官网及中国知网入口为准。'},
 '美国大学生数学建模竞赛': {'url': 'https://www.comap.com/contests/mcm-icm',
                 'timeline': 'MCM/ICM 通常在每年 1-2 月举行，注册、比赛和论文提交以 COMAP 当年 Contest Calendar 为准。'},
 '“蓝桥杯”全国软件和信息技术专业人才大赛': {'url': 'https://dasai.lanqiao.cn/',
                          'timeline': '报名通常在每年 10-12 月，省赛一般在次年 4 月，总决赛一般在 5 月底或 6 月；以蓝桥杯官网通知为准。'},
 '全国大学生电子设计竞赛': {'url': 'https://nuedc.xjtu.edu.cn/',
                 'timeline': '全国赛通知通常提前发布，2025 年全国赛在暑期组织；专题赛和复测以全国大学生电子设计竞赛官网通知为准。'},
 '中国大学生计算机设计大赛': {'url': 'https://jsjds.blcu.edu.cn/', 'timeline': '省级赛通知通常在春季汇集，国赛启动和作品提交要求以中国大学生计算机设计大赛官网年度通知为准。'},
 '全国大学生信息安全竞赛': {'url': 'https://www.ciscn.cn/', 'timeline': '创新实践能力赛和作品赛节点以全国大学生信息安全竞赛官网年度通知为准。'},
 '全国大学生机器人大赛—RoboMaster、RoboCon': {'url': 'https://www.robomaster.com/',
                                   'timeline': 'RoboMaster/RoboCon 分赛项报名、区域赛和总决赛安排以大疆 RoboMaster 与相关赛事官方通知为准。'},
 '中国软件杯”大学生软件设计大赛': {'url': 'https://www.cnsoftbei.com/', 'timeline': '报名、初赛、决赛和获奖公示以中国软件杯官网当届通知为准。'}}
